---
spring:
  profiles: eureka-peer1
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-peer1
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      default-zone:
        http://eureka-peer2:8762/eureka/

---
spring:
  profiles: eureka-peer2
server:
  port: 8762

eureka:
  instance:
    hostname: eureka-peer2
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      default-zone:
        http://eureka-peer1:8761/eureka/





